---
# handlers file for jenkins

- name: restart zabbix server
  service: name=zabbix-server state=restarted

- name: restart httpd
  service: name=httpd state=restarted

- name: restart mysqld
  service: name=mysqld state=restarted


- name: start httpd
  service: name=httpd state=started
